name = "adapnow-site"
account_id = "720ec85be65a483a3e34400d56dba5d8"

main = ".open-next/worker.js"

compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
