// scripts/genSchemaIndex.mjs
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SCHEMA_DIR = path.join(ROOT, "src", "lib", "db", "schema");
const OUT_FILE = path.join(SCHEMA_DIR, "index.ts");

// Always skip these
const ALWAYS_SKIP = new Set([
  "index.ts",
  "index.js",
  "index.mjs",
]);

function isTsFile(name) {
  return name.endsWith(".ts") && !name.endsWith(".d.ts");
}

function baseName(file) {
  return file.replace(/\.ts$/, "");
}

function exists(file) {
  return fs.existsSync(path.join(SCHEMA_DIR, file));
}

/**
 * If a "barrel" exists, skip leaf modules that it already re-exports.
 * This prevents TS2308 duplicate export name collisions in schema/index.ts.
 */
function computeDynamicSkips() {
  const skip = new Set();

  // If customer.ts is the barrel, skip leaf modules it re-exports
  if (exists("customer.ts")) {
    [
      "customerAddresses.ts",
      "loyalty.ts",
      "orders.ts",
      "orderItems.ts",
    ].forEach((f) => {
      if (exists(f)) skip.add(f);
    });
  }

  // If reviews.ts is the barrel, skip leaf modules it re-exports
  if (exists("reviews.ts")) {
    [
      "productReviews.ts",
      "reviewHelpfulVotes.ts",
    ].forEach((f) => {
      if (exists(f)) skip.add(f);
    });
  }

  // If uploads.ts is the barrel, skip leaf modules it re-exports
  if (exists("uploads.ts")) {
    ["artworkUploads.ts"].forEach((f) => {
      if (exists(f)) skip.add(f);
    });
  }

  return skip;
}

function main() {
  if (!fs.existsSync(SCHEMA_DIR)) {
    console.error(`Schema dir not found: ${SCHEMA_DIR}`);
    process.exit(1);
  }

  const dynamicSkips = computeDynamicSkips();

  const files = fs
    .readdirSync(SCHEMA_DIR)
    .filter((f) => isTsFile(f))
    .filter((f) => !ALWAYS_SKIP.has(f))
    .filter((f) => !dynamicSkips.has(f))
    .sort((a, b) => a.localeCompare(b));

  const header = `// src/lib/db/schema/index.ts
// AUTO-GENERATED by scripts/genSchemaIndex.mjs
// Do not edit by hand — run: node scripts/genSchemaIndex.mjs

`;

  const body = files.map((f) => `export * from "./${baseName(f)}";`).join("\n") + "\n";

  fs.writeFileSync(OUT_FILE, header + body, "utf8");

  console.log(`✅ Wrote ${path.relative(ROOT, OUT_FILE)} with ${files.length} exports.`);
  if (dynamicSkips.size) {
    console.log(`ℹ️  Skipped (barrel duplicates): ${Array.from(dynamicSkips).sort().join(", ")}`);
  }
}

main();
